export default {
    request: {
        country: 'uk',
        language: 'en',
        location: 'brighton',
        num_res: '20',
        offset: 0,
        output: 'json_xs',
        page: 1,
        pretty: '1',
        product_type: 'realestate',
        property_type: 'property',
        size_type: 'net',
        size_unit: 'm2',
        sort: 'nestoria_rank',
        listing_type: 'buy'
    },
    response: {
        application_response_code: '100',
        application_response_text:
            'listings returned for one unambiguous location',
        attribution: {
            img_height: 22,
            img_url: 'https://resources.nestimg.com/nestoria/img/pbr_v1.png',
            img_width: 183,
            link_to_img: 'http://www.nestoria.com'
        },
        created_http: 'Sun, 31 May 2020 21:20:29 GMT',
        created_unix: 1590960029,
        link_to_url: 'https://www.nestoria.co.uk/brighton/property/buy',
        listings: [
            {
                bathroom_number: '',
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_terraced_house_112379427420803939.jpg',
                img_width: 400,
                keywords:
                    'Garden, Terraced, Kitchen, Parking, Patio, Cottage, Reception',
                latitude: 50.843014,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000000112379427420803939/title/5/1-1?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1527262,
                price: 400000,
                price_currency: '£',
                price_formatted: '£400,000',
                price_high: 400000,
                price_low: 400000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Situated on a desirable road close to many local amenities is this ...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_terraced_house_112379427420803939.jpg',
                thumb_width: 80,
                title: 'North Road, Preston, Brighton, BN1',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: 0,
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'PropertyHeads',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_merton_court_the_strand_brighton_bn2_7130092590918036263.jpg',
                img_width: 400,
                keywords: 'New Build, Balcony, Parking',
                latitude: 50.8116,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007130092590918036263/title/5/1-2?serpUid=&pt=1&ot=1&l=brighton&did=370854_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.099033,
                price: 379950,
                price_currency: '£',
                price_formatted: '£379,950',
                price_high: 379950,
                price_low: 379950,
                price_type: 'fixed',
                property_type: 'flat',
                room_number: 2,
                size: 0,
                size_type: 'net',
                summary:
                    'This spectaular newly overhauled 2 bedroom 2 bathroom top floor apa...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_merton_court_the_strand_brighton_bn2_7130092590918036263.jpg',
                thumb_width: 80,
                title: 'Merton Court, The Strand, Brighton BN2',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: '',
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_property_1550038590917815930.jpg',
                img_width: 400,
                keywords:
                    'Freehold, Garden, Maisonette, Kitchen, Loft, Parking, Gas Central Heating',
                latitude: 50.84095,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000001550038590917815930/title/5/1-3?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1179376,
                price: 290000,
                price_currency: '£',
                price_formatted: '£290,000',
                price_high: 290000,
                price_low: 290000,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'This is an opportunity to get your hands on a well presented 2-bedr...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_property_1550038590917815930.jpg',
                thumb_width: 80,
                title: 'Buller Road, Brighton, BN2 - Garden',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: 2,
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_apartment_flat_6640038590917827567.jpg',
                img_width: 400,
                keywords: 'New Build, Balcony, Parking',
                latitude: 50.811584,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000006640038590917827567/title/5/1-4?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0990323,
                price: 379950,
                price_currency: '£',
                price_formatted: '£379,950',
                price_high: 379950,
                price_low: 379950,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'This spectaular newly overhauled 2 bedroom 2 bathroom top floor apa...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_apartment_flat_6640038590917827567.jpg',
                thumb_width: 80,
                title: 'The Strand, Brighton Marina Village, Brighton, BN2',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: '',
                bedroom_number: 5,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/5_bedroom_detached_house_6780038590916837309.jpg',
                img_width: 400,
                keywords:
                    'Detached, Garden, En suite, Fireplace, Double Bedroom, Kitchen',
                latitude: 50.816387,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000006780038590916837309/title/5/1-5?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1024147,
                price: 2000000,
                price_currency: '£',
                price_formatted: '£2,000,000',
                price_high: 2000000,
                price_low: 2000000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'In a highly sought after roedean location, sleek electric gates swe...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/5_bedroom_detached_house_6780038590916837309.jpg',
                thumb_width: 80,
                title: 'Roedean Road, Brighton, East Sussex, BN2',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: '',
                bedroom_number: 1,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/1_bedroom_flat_3640038590917408102.jpg',
                img_width: 400,
                keywords: 'Fireplace, High Ceilings, Kitchen',
                latitude: 50.819046,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000003640038590917408102/title/5/1-6?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1288273,
                price: 215000,
                price_currency: '£',
                price_formatted: '£215,000',
                price_high: 215000,
                price_low: 215000,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'This 1 bedroom flat has infinitely high ceilings and an large loung...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/1_bedroom_flat_3640038590917408102.jpg',
                thumb_width: 80,
                title: 'Marine Parade, Brighton, BN2',
                updated_in_days: 0,
                updated_in_days_formatted: 'New'
            },
            {
                bathroom_number: '',
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_terraced_house_7070130590832072107.jpg',
                img_width: 400,
                keywords:
                    'Garden, Fireplace, Terraced, Wood Floor, Double Bedroom, Kitchen, Parking',
                latitude: 50.82891,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007070130590832072107/title/5/1-7?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1244426,
                price: 410000,
                price_currency: '£',
                price_formatted: '£410,000',
                price_high: 410000,
                price_low: 410000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'A two-bedroom terraced townhouse in the vibrant region of hanover, ...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_terraced_house_7070130590832072107.jpg',
                thumb_width: 80,
                title: 'Whichelo Place, Brighton, East Sussex, BN2',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 6,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/6_bedroom_property_5640130590832318135.jpg',
                img_width: 400,
                keywords:
                    'Detached, Garden, Fireplace, Kitchen, Off Street Parking, Cottage',
                latitude: 50.81023,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000005640130590832318135/title/5/1-8?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0506838,
                price: 2500000,
                price_currency: '£',
                price_formatted: '£2,500,000',
                price_high: 2500000,
                price_low: 2500000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    '5 bedroom detached house with separate bedroom cottage 4 bathrooms ...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/6_bedroom_property_5640130590832318135.jpg',
                thumb_width: 80,
                title: 'Dean Court Road, Rottingdean, Brighton, BN2',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 3,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/3_bedroom_semi_detached_house_2800130590832284456.jpg',
                img_width: 400,
                keywords:
                    'Garden, Needs Modernisation, Semi-Detached, High Ceilings, Terraced, Double Bedroom, Kitchen, Modern',
                latitude: 50.83438,
                lister_name: 'Phillips & Still',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000002800130590832284456/title/5/1-9?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1481392,
                price: 700000,
                price_currency: '£',
                price_formatted: '£700,000',
                price_high: 700000,
                price_low: 700000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Rare opportunity to purchase an entire end of terrace period buildi...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/3_bedroom_semi_detached_house_2800130590832284456.jpg',
                thumb_width: 80,
                title: 'Lancaster Road, Brighton, BN1',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 3,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/3_bedroom_semi_detached_bungalow_7230130590832162714.jpg',
                img_width: 400,
                keywords:
                    'Garden, Semi-Detached, En suite, Conversion, Garage, Kitchen, Bungalow, Modern',
                latitude: 50.86041,
                lister_name: 'Cubit & West',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007230130590832162714/title/5/1-10?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1228097,
                price: 500000,
                price_currency: '£',
                price_formatted: '£500,000',
                price_high: 500000,
                price_low: 500000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Pretty extended semi-detached bungalow with ly modern open plan kit...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/3_bedroom_semi_detached_bungalow_7230130590832162714.jpg',
                thumb_width: 80,
                title: 'Ditchling Crescent, Brighton, East Sussex, BN1',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 3,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/3_bedroom_semi_detached_bungalow_3760040589448174056.jpg',
                img_width: 400,
                keywords:
                    'Garden, Semi-Detached, Conversion, Garage, Kitchen, Bungalow',
                latitude: 50.815605,
                lister_name: 'Cubit & West',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000003760040589448174056/title/5/1-11?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0667715,
                price: 325000,
                price_currency: '£',
                price_formatted: '£325,000',
                price_high: 325000,
                price_low: 325000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'This semi detached home has bags of potential, on a pleasant plot w...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/3_bedroom_semi_detached_bungalow_3760040589448174056.jpg',
                thumb_width: 80,
                title:
                    'Elvin Crescent, Rottingdean, Brighton, East Sussex, BN2',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 3,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/3_bedroom_terraced_house_1830130590832339724.jpg',
                img_width: 400,
                keywords: 'Garden, Conservatory, Terraced, Kitchen, Patio',
                latitude: 50.83468,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000001830130590832339724/title/5/1-12?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.2233685,
                price: 325000,
                price_currency: '£',
                price_formatted: '£325,000',
                price_high: 325000,
                price_low: 325000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    '3 bedroom mid-terraced family home in sought after school catchment...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/3_bedroom_terraced_house_1830130590832339724.jpg',
                thumb_width: 80,
                title: 'Old Barn Way, Southwick, Brighton, BN42',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_flat_7580130590832162873.jpg',
                img_width: 400,
                keywords:
                    'Shared Garden, Freehold, Conversion, Kitchen, Parking',
                latitude: 50.806248,
                lister_name: 'Cubit & West',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007580130590832162873/title/5/1-13?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0385013,
                price: 265000,
                price_currency: '£',
                price_formatted: '£265,000',
                price_high: 265000,
                price_low: 265000,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'Video walk around available, contact branch for details unpack your...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_flat_7580130590832162873.jpg',
                thumb_width: 80,
                title: 'Lustrells Vale, Saltdean, Brighton, East Sussex, BN2',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 3,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/3_bedroom_bungalow_7490046585391410121.jpg',
                img_width: 400,
                keywords:
                    'Garden, Needs Modernisation, Semi-Detached, No Chain, Garage, Kitchen, Bungalow',
                latitude: 50.815605,
                lister_name: 'King & Chasemore',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007490046585391410121/title/5/1-14?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0667715,
                price: 325000,
                price_currency: '£',
                price_formatted: '£325,000',
                price_high: 325000,
                price_low: 325000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Three beds with garage and private driveway no chain in need of som...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/3_bedroom_bungalow_7490046585391410121.jpg',
                thumb_width: 80,
                title:
                    'Elvin Crescent, Rottingdean, Brighton, East Sussex, BN2',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: '',
                bedroom_number: 1,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/1_bedroom_flat_3120130590832284559.jpg',
                img_width: 400,
                keywords: 'Garden, Conversion, High Ceilings, Kitchen',
                latitude: 50.83274,
                lister_name: 'Phillips & Still',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000003120130590832284559/title/5/1-15?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1484739,
                price: 265000,
                price_currency: '£',
                price_formatted: '£265,000',
                price_high: 265000,
                price_low: 265000,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'One bedroom converted first floor residence situated in one of brig...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/1_bedroom_flat_3120130590832284559.jpg',
                thumb_width: 80,
                title: 'Belmont, Brighton, BN1 - Garden',
                updated_in_days: 1,
                updated_in_days_formatted: 'first seen yesterday'
            },
            {
                bathroom_number: 0,
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'PropertyHeads',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_waterfront_brighton_marina_village_brighton_bn2_8920086580818785444.jpg',
                img_width: 400,
                keywords: '',
                latitude: 50.8128,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000008920086580818785444/title/5/1-16?serpUid=&pt=1&ot=1&l=brighton&did=370854_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.10219,
                price: 100000,
                price_currency: '£',
                price_formatted: '£100,000',
                price_high: 100000,
                price_low: 100000,
                price_type: 'fixed',
                property_type: 'flat',
                room_number: 2,
                size: 0,
                size_type: 'net',
                summary:
                    'A opportunity to be part of a new concept for brighton marina and b...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_waterfront_brighton_marina_village_brighton_bn2_8920086580818785444.jpg',
                thumb_width: 80,
                title: 'Waterfront, Brighton Marina Village, Brighton BN2',
                updated_in_days: 2,
                updated_in_days_formatted: 'first seen 2 days ago'
            },
            {
                bathroom_number: '',
                bedroom_number: 4,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/4_bedroom_terraced_house_7020133583664964137.jpg',
                img_width: 400,
                keywords:
                    'Garden, Terraced, Double Bedroom, Kitchen, Modern, Patio',
                latitude: 50.82656,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007020133583664964137/title/5/1-17?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1444018,
                price: 650000,
                price_currency: '£',
                price_formatted: '£650,000',
                price_high: 650000,
                price_low: 650000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Price range 650,000 to 700,00. A 4 storey bay fronted period terrac...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/4_bedroom_terraced_house_7020133583664964137.jpg',
                thumb_width: 80,
                title: 'St Nicholas Road, Brighton, East Sussex, BN1',
                updated_in_days: 2,
                updated_in_days_formatted: 'first seen 2 days ago'
            },
            {
                bathroom_number: '',
                bedroom_number: 1,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/1_bedroom_ground_flat_3940041590744340070.jpg',
                img_width: 400,
                keywords: 'Conversion, Kitchen, Parking',
                latitude: 50.837196,
                lister_name: 'Cubit & West',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000003940041590744340070/title/5/1-18?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.1414802,
                price: 260000,
                price_currency: '£',
                price_formatted: '£260,000',
                price_high: 260000,
                price_low: 260000,
                price_type: 'fixed',
                property_type: 'flat',
                size: 0,
                size_type: 'net',
                summary:
                    'Ly presented, light and bright flat close to preston park with allo...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/1_bedroom_ground_flat_3940041590744340070.jpg',
                thumb_width: 80,
                title: 'Stanford Avenue, Brighton, East Sussex, BN1',
                updated_in_days: 2,
                updated_in_days_formatted: 'first seen 2 days ago'
            },
            {
                bathroom_number: 0,
                bedroom_number: 5,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'PropertyHeads',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/5_bedroom_the_cliff_approach_brighton_east_sussex_bn2_8860086580818785422.jpg',
                img_width: 400,
                keywords: 'No Chain, Wood Floor, Kitchen, Patio',
                latitude: 50.8162,
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000008860086580818785422/title/5/1-19?serpUid=&pt=1&ot=1&l=brighton&did=370854_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.102438,
                price: 950000,
                price_currency: '£',
                price_formatted: '£950,000',
                price_high: 950000,
                price_low: 950000,
                price_type: 'fixed',
                property_type: 'house',
                room_number: 5,
                size: 0,
                size_type: 'net',
                summary:
                    'A remarkably and ly presented eco house with eco credentials on a c...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/5_bedroom_the_cliff_approach_brighton_east_sussex_bn2_8860086580818785422.jpg',
                thumb_width: 80,
                title: 'The Cliff Approach, Brighton, East Sussex BN2',
                updated_in_days: 2,
                updated_in_days_formatted: 'first seen 2 days ago'
            },
            {
                bathroom_number: '',
                bedroom_number: 2,
                car_spaces: '',
                commission: 0,
                construction_year: 0,
                datasource_name: 'NetHousePrices',
                img_height: 300,
                img_url:
                    'https://imgs.nestimg.com/2_bedroom_terraced_house_7510120582109926572.jpg',
                img_width: 400,
                keywords:
                    'Garden, Conversion, Terraced, Kitchen, Off Street Parking, Cul-de-Sac',
                latitude: 50.83985,
                lister_name: 'Cubit & West',
                lister_url:
                    'https://www.nestoria.co.uk/detail-int/0000007510120582109926572/title/5/1-20?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external',
                listing_type: 'buy',
                location_accuracy: 9,
                longitude: -0.0689654,
                price: 295000,
                price_currency: '£',
                price_formatted: '£295,000',
                price_high: 295000,
                price_low: 295000,
                price_type: 'fixed',
                property_type: 'house',
                size: 0,
                size_type: 'net',
                summary:
                    'Perfect first time buyer home in a cul de sac, with off street park...',
                thumb_height: 60,
                thumb_url:
                    'https://imgs.nestimg.com/medium/2_bedroom_terraced_house_7510120582109926572.jpg',
                thumb_width: 80,
                title: 'Marden Close, Brighton, East Sussex, BN2',
                updated_in_days: 3,
                updated_in_days_formatted: 'first seen 3 days ago'
            }
        ],
        locations: [
            {
                center_lat: 50.854603,
                center_long: -0.132899,
                long_title: 'Brighton',
                place_name: 'brighton',
                title: 'Brighton'
            }
        ],
        page: 1,
        sort: 'nestoria_rank',
        status_code: '200',
        status_text: 'OK',
        thanks: 'For using the Nestoria API.',
        total_pages: 93,
        total_results: 1853,
        _cu5t0mP434m_: 'remove'
    }
};
